### ISSUE TITLE
Unable to compile?

### ISSUE THREAD

**Issue by Arinerron** [LLK/scratch-flash#1152]
When I run `./gradlew build -Ptarget=10.2 --stacktrace --debug
`, it says `Redirection detected from https to http. Protocol switch unsafe, not allowed.`

Here's more info:

```
[get] https://sourceforge.net/projects/osmf.adobe/files/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip/download moved to http://downloads.sourceforge.net/project/osmf.adobe/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip?r=&ts=1466789558&use_mirror=pilotfiber
reverting SDK installation

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'scratch-flash-master'.
> The following error occurred while executing this line:
  /home/<snip>/.gradle/gradleFx/sdks/e71cbc0c58bb8ec5deb902a0564cc290f53a6276/frameworks/downloads.xml:125: The following error occurred while executing this line:
  /home/<snip>/.gradle/gradleFx/sdks/e71cbc0c58bb8ec5deb902a0564cc290f53a6276/frameworks/downloads.xml:144: Redirection detected from https to http. Protocol switch unsafe, not allowed.

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'scratch-flash-master'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:488)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:143)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:47)
	at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLauncher.java:189)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:140)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:104)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleLauncher.java:184)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:93)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:27)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:72)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:44)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: : The following error occurred while executing this line:
/home/<snip>/.gradle/gradleFx/sdks/e71cbc0c58bb8ec5deb902a0564cc290f53a6276/frameworks/downloads.xml:125: The following error occurred while executing this line:
/home/<snip>/.gradle/gradleFx/sdks/e71cbc0c58bb8ec5deb902a0564cc290f53a6276/frameworks/downloads.xml:144: Redirection detected from https to http. Protocol switch unsafe, not allowed.
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:568)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.gradlefx.configuration.sdk.states.flex.InstallFlexSdkState.executeSdkDownloadsScript(InstallFlexSdkState.groovy:85)
	at org.gradlefx.configuration.sdk.states.flex.InstallFlexSdkState.downloadSdkDependencies(InstallFlexSdkState.groovy:46)
	at org.gradlefx.configuration.sdk.states.AbstractInstallSdkState.process(AbstractInstallSdkState.groovy:56)
	at org.gradlefx.configuration.sdk.SdkInitState$process.call(Unknown Source)
	at org.gradlefx.configuration.sdk.SdkInitState$process.call(Unknown Source)
	at org.gradlefx.configuration.sdk.DefaultSdkInitialisationContext.initSdk(DefaultSdkInitialisationContext.groovy:33)
	at org.gradlefx.configuration.sdk.SdkInitialisationContext$initSdk.call(Unknown Source)
	at org.gradlefx.plugins.GradleFxPlugin.initializeSDKs(GradleFxPlugin.groovy:87)
	at org.gradlefx.plugins.GradleFxPlugin.configure(GradleFxPlugin.groovy:70)
	at org.gradlefx.plugins.AbstractGradleFxPlugin$_apply_closure1.doCall(AbstractGradleFxPlugin.groovy:50)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	... 45 more
Caused by: /home/<snip>/.gradle/gradleFx/sdks/e71cbc0c58bb8ec5deb902a0564cc290f53a6276/frameworks/downloads.xml:125: The following error occurred while executing this line:
/home/<snip>/.gradle/gradleFx/sdks/e71cbc0c58bb8ec5deb902a0564cc290f53a6276/frameworks/downloads.xml:144: Redirection detected from https to http. Protocol switch unsafe, not allowed.
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:568)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
	... 64 more
Caused by: /home/<snip>/.gradle/gradleFx/sdks/e71cbc0c58bb8ec5deb902a0564cc290f53a6276/frameworks/downloads.xml:144: Redirection detected from https to http. Protocol switch unsafe, not allowed.
	at org.apache.tools.ant.taskdefs.Get$GetThread.redirectionAllowed(Get.java:637)
	at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:711)
	at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:715)
	at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:606)
	at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:596)


BUILD FAILED

Total time: 26.966 secs
```

This happens while compiling this repo, and I need to compile my own copy (for reasons). It'd be great if I could have some help. Thanks!

My OS details: `Linux Mint 17.3 Cinnamon 64-bit`

**Comment by elianabdelmajid** [comment]
Hi, you should make the directory and get manually the package you need: 

First step: `mkdir -p /home/**yourusername**/.gradle/gradleFx/sdks/c88d5bcd374ee0cb5c638313527bca6683068120/in/
`

Second step: 
 `wget http://sourceforge.net/projects/osmf.adobe/files/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip/download -O /home/**yourusername**/.gradle/gradleFx/sdks/YOUR_NUMBER/in/OSMF_1.0.zip`

In your case, your number is: e71cbc0c58bb8ec5deb902a0564cc290f53a6276

**Comment by motdotla** [comment]
Thank you for this. Is there a reason the build script can't be adjusted to support the https to http redirect - even as a 'one off' whitelisted redirect?
